# Generated by Django 4.0.5 on 2022-06-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=300)),
                ('page_url', models.CharField(default='', max_length=200)),
                ('img_url', models.CharField(default='', max_length=200)),
                ('content_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
