# Generated by Django 4.0.5 on 2022-06-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_model_alter_body_img_url_alter_body_page_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='caption',
        ),
    ]
