# Generated by Django 4.0.5 on 2022-06-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_model_caption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Model_3D',
        ),
    ]
