# Generated by Django 4.0.5 on 2022-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_model_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_3d',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
